# This file is generated by the Geant4 CMake buildsystem and should not be editted
#
# This file stores paths and settings to external libraries found and used by this
# install of Geant4 when it was built.

macro(geant4_set_and_check_package_variable _name _value _type _docstring)
    if(DEFINED ${_name})
        if(NOT ("${${_name}}" STREQUAL "${_value}"))
            message(WARNING "Value of '${_name}' is already set and does not match value set at Geant4 build-time")
        endif()
    else()
        set(${_name} ${_value} CACHE ${_type} "${_docstring}")
    endif()
endmacro()

# XercesC Build Time Settings
geant4_set_and_check_package_variable(XercesC_INCLUDE_DIR "/opt/projects/ceInstall/macosx15-clang16/xercesc/3.2.5/include" PATH "Xerces-C++ include directory")
geant4_set_and_check_package_variable(XercesC_LIBRARY_RELEASE "/opt/projects/ceInstall/macosx15-clang16/xercesc/3.2.5/lib/libxerces-c.dylib" FILEPATH "Xerces-C++ libraries (release)")

